//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevTreks.Exceptions {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevTreks.Exceptions.ErrorMessages", typeof(ErrorMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An observation is missing from the analysis. Please make sure that calculations have been run on all observations. Also make sure that the type of calculation selected is appropriate for this analysis..
        /// </summary>
        internal static string ADDIN_MISSINGOBSERVATION {
            get {
                return ResourceManager.GetString("ADDIN_MISSINGOBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The database list of custom documents being analyzed could not be found. Does this analysis have actual files to analyze?.
        /// </summary>
        internal static string ADDIN_NOANALYSISLIST {
            get {
                return ResourceManager.GetString("ADDIN_NOANALYSISLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either the summary document used to verify analyses has not been made yet or you have not made a correct selection below. Make sure to run a base calculator before running an analysis and make sure that the &quot;Base Calculator&quot; or &quot;Related Calculator&quot; selection is correct for the analyses being run..
        /// </summary>
        internal static string ADDIN_NOSUMMARYDOC {
            get {
                return ResourceManager.GetString("ADDIN_NOSUMMARYDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A document needed to run the calculations is missing..
        /// </summary>
        internal static string ADDINHELPER_MISSINGDOC {
            get {
                return ResourceManager.GetString("ADDINHELPER_MISSINGDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The type of files being analyzed could not be determined. Has the base calculator been run?.
        /// </summary>
        internal static string ADDINHELPER_NOBASECALCS {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOBASECALCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator does not have a required Type attribute..
        /// </summary>
        internal static string ADDINHELPER_NOCALCTYPE {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOCALCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator file could not be found. Please be sure that the calculator being used has a default calculator document..
        /// </summary>
        internal static string ADDINHELPER_NOCALCULATOR {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOCALCULATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Files could not be found to analyze. Are you sure that devpackpart files have been added to the database?.
        /// </summary>
        internal static string ADDINHELPER_NODEVPACKPARTS {
            get {
                return ResourceManager.GetString("ADDINHELPER_NODEVPACKPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator does not have a needed file extension type..
        /// </summary>
        internal static string ADDINHELPER_NOFILEEXTENSIONTYPE {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOFILEEXTENSIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file path to the selected linked view could not be determined..
        /// </summary>
        internal static string ADDINSTATE_NOADDINDOC {
            get {
                return ResourceManager.GetString("ADDINSTATE_NOADDINDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The chosen calculator or analyzer no longer exists. Please change to another one..
        /// </summary>
        internal static string ADDINSTATE_NOADDINDOC2 {
            get {
                return ResourceManager.GetString("ADDINSTATE_NOADDINDOC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file path to the initial document being viewed could not be determined..
        /// </summary>
        internal static string ADDINSTATE_NOINITDOC {
            get {
                return ResourceManager.GetString("ADDINSTATE_NOINITDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The linked view that you selected was not set correctly..
        /// </summary>
        internal static string ADDINSTATE_NOSELECTEDVIEWDOC {
            get {
                return ResourceManager.GetString("ADDINSTATE_NOSELECTEDVIEWDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stylesheet for this analysis could not be found. Please run another analysis and save the results..
        /// </summary>
        internal static string ADDINSTYLE_NOSTYLESHEET {
            get {
                return ResourceManager.GetString("ADDINSTYLE_NOSTYLESHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The parent node does not accept child nodes of the type being added..
        /// </summary>
        internal static string ADDS_CANTADDCHILDTOPARENT {
            get {
                return ResourceManager.GetString("ADDS_CANTADDCHILDTOPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The temporary document needed to hold the selections could not be built (due to a namespace issue)..
        /// </summary>
        internal static string ADDS_CANTBUILDTEMPDOC {
            get {
                return ResourceManager.GetString("ADDS_CANTBUILDTEMPDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One of the nodes selected could not be added..
        /// </summary>
        internal static string ADDS_COULDNOTADDELEMENT {
            get {
                return ResourceManager.GetString("ADDS_COULDNOTADDELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One of the nodes inserted could not be found in the original list of nodes needing to be inserted. This will interfere with any pending database insertion..
        /// </summary>
        internal static string ADDS_MISSINGFROMSELECTIONSLIST {
            get {
                return ResourceManager.GetString("ADDS_MISSINGFROMSELECTIONSLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find an ancestor for one of the selections being added..
        /// </summary>
        internal static string ADDS_NOANCESTORFOUND {
            get {
                return ResourceManager.GetString("ADDS_NOANCESTORFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No database record could be found for one of the selections..
        /// </summary>
        internal static string ADDS_NODBRECORD {
            get {
                return ResourceManager.GetString("ADDS_NODBRECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The xml document used to start this story does not have a default node with an Id = 1 for the node you are trying to add..
        /// </summary>
        internal static string ADDS_NODEFAULTNODETOCOPY {
            get {
                return ResourceManager.GetString("ADDS_NODEFAULTNODETOCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A grouping ancestor (i.e. outputs) could not be built..
        /// </summary>
        internal static string ADDS_NOGROUPINGANCESTORFOUND {
            get {
                return ResourceManager.GetString("ADDS_NOGROUPINGANCESTORFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The return ids needed for inserting nodes could not be found..
        /// </summary>
        internal static string ADDS_NORETURNIDS {
            get {
                return ResourceManager.GetString("ADDS_NORETURNIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One of the selections could not be retrieved. Please try another selection..
        /// </summary>
        internal static string ADDS_NOSELECTION {
            get {
                return ResourceManager.GetString("ADDS_NOSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Selections were not available for making insertions. Please resubmit..
        /// </summary>
        internal static string ADDS_NOSELECTIONS {
            get {
                return ResourceManager.GetString("ADDS_NOSELECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not get the sqlxml parameters needed to run this query..
        /// </summary>
        internal static string ADDS_NOSQLPARAMS {
            get {
                return ResourceManager.GetString("ADDS_NOSQLPARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file for adding the selections could not be found -a possible reason is that its using an old name that is not currently allowed by DevTreks..
        /// </summary>
        internal static string ADDSELECTS_NOFILE {
            get {
                return ResourceManager.GetString("ADDSELECTS_NOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file could not be uploaded. A non-standard error has been logged. Please inform DevTreks about the time and circumstance of the error..
        /// </summary>
        internal static string APPHELPER_NOFILEUPLOAD {
            get {
                return ResourceManager.GetString("APPHELPER_NOFILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A non-standard error has been logged. Please inform DevTreks about the time and circumstance of the error..
        /// </summary>
        internal static string APPHELPER_WHOKNOWS {
            get {
                return ResourceManager.GetString("APPHELPER_WHOKNOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The package could not be save in the cloud (in a blob in the cloud)..
        /// </summary>
        internal static string BLOB_CANTSAVEZIPBLOB {
            get {
                return ResourceManager.GetString("BLOB_CANTSAVEZIPBLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator being used has no nodes with the required name of &apos;linkedview&apos;. Please have the calculator owner recheck their calculator node names..
        /// </summary>
        internal static string CALCDOC_NOLINKEDVIEWNODES {
            get {
                return ResourceManager.GetString("CALCDOC_NOLINKEDVIEWNODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file could not be uploaded because the application-node combination you are using do not support file uploads..
        /// </summary>
        internal static string CONTENTHELPER_FILENOUPLOAD {
            get {
                return ResourceManager.GetString("CONTENTHELPER_FILENOUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculations could not be saved..
        /// </summary>
        internal static string CONTENTHELPER_NOSAVECALCS {
            get {
                return ResourceManager.GetString("CONTENTHELPER_NOSAVECALCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The selected view does not have a required parent uri pattern..
        /// </summary>
        internal static string CONTENTHELPER_SELECTHASNOPARENT {
            get {
                return ResourceManager.GetString("CONTENTHELPER_SELECTHASNOPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The uri you are trying to edit has a bad initial application type. Please try loading this uri again..
        /// </summary>
        internal static string CONTENTREP_BADAPP {
            get {
                return ResourceManager.GetString("CONTENTREP_BADAPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The selections could not be saved..
        /// </summary>
        internal static string CONTENTSERVICE_CANTSAVESELECTS {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_CANTSAVESELECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The base xml document needed to begin running calculations has been successfully built. The calculations can now be run..
        /// </summary>
        internal static string CONTENTSERVICE_HASNEWXMLDOC {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_HASNEWXMLDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculations could not be run. Please make sure the addin names are correct in the calculator being used (i.e. the linkedview&apos;s host name and add-in name)..
        /// </summary>
        internal static string CONTENTSERVICE_NOCALCSRUN {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_NOCALCSRUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculations can not be run. In this release, calculators and analyzers only run when linked to other uris, not stand-alone..
        /// </summary>
        internal static string CONTENTSERVICE_NOCALCSRUN2 {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_NOCALCSRUN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The form parameters needed to add default nodes was not available. Please try again..
        /// </summary>
        internal static string CONTENTSERVICE_NOFORMELS {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_NOFORMELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The selected linked view could not be loaded for editing. Please try again..
        /// </summary>
        internal static string CONTENTSERVICE_NOLINKEDVIEW {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_NOLINKEDVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The selected linked views could not be added to the node. Are you selecting linkedview nodes?.
        /// </summary>
        internal static string CONTENTSERVICE_NOLINKEDVIEWADD {
            get {
                return ResourceManager.GetString("CONTENTSERVICE_NOLINKEDVIEWADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please make an edit before clicking on the submit edit button. .
        /// </summary>
        internal static string CONTENTVIEW_MAKEEDIT {
            get {
                return ResourceManager.GetString("CONTENTVIEW_MAKEEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please make an edit before clicking on the submit edit button. Also close any form that is open in the linked views panel..
        /// </summary>
        internal static string CONTENTVIEW_MAKEEDIT2 {
            get {
                return ResourceManager.GetString("CONTENTVIEW_MAKEEDIT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A file was not received on the server. Please try uploading it again..
        /// </summary>
        internal static string CONTENTVIEW_NOFILEUPLOAD {
            get {
                return ResourceManager.GetString("CONTENTVIEW_NOFILEUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You tried to delete the last member of a club. The associated club must also be deleted but could not be, probably because it still holds undeleted data. First delete all of the data associated with the club and then try to delete the last member of the club..
        /// </summary>
        internal static string DELETE_LASTCLUBMEMBER {
            get {
                return ResourceManager.GetString("DELETE_LASTCLUBMEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The node being deleted could not be found..
        /// </summary>
        internal static string DELETE_NOTFOUND {
            get {
                return ResourceManager.GetString("DELETE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One of the services or incentives could not be deleted. Please try again..
        /// </summary>
        internal static string DELETESERVICE_FAIL {
            get {
                return ResourceManager.GetString("DELETESERVICE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The directory you are trying to use does not exist yet..
        /// </summary>
        internal static string DIRECTORY_NOEXIST {
            get {
                return ResourceManager.GetString("DIRECTORY_NOEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The media url must be copied from the link associated with Download Resource buttons..
        /// </summary>
        internal static string DISPLAYHELPER_BADMEDIAURL {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_BADMEDIAURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Use the second Get command to display the results for a specific calculator or analyzer..
        /// </summary>
        internal static string DISPLAYHELPER_DEVPACKSINIT {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_DEVPACKSINIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No display is needed by this step..
        /// </summary>
        internal static string DISPLAYHELPER_DONTNEEDHTMLDOC {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_DONTNEEDHTMLDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The linked view could not be found. Has a specific linked view been opened? Are you sure that the linked view has been linked to the view selected? If linked views are available in the selection box above, please try running and saving the linked views..
        /// </summary>
        internal static string DISPLAYHELPER_NOADDIN {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOADDIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculated results do not exist. Make sure to build a base document if one has not already been built. Please try running the calculations, or asking the owner to run the calculations. Make sure that you clicked the Get AddIn link to open the calculator or analyzer..
        /// </summary>
        internal static string DISPLAYHELPER_NOCALCULATIONS {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOCALCULATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The node you are on has no data. If it is a linked view&apos;s resources, please go back to the linked view itself..
        /// </summary>
        internal static string DISPLAYHELPER_NODOCFORTHISNODE {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NODOCFORTHISNODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An html file could not be made. Please try again..
        /// </summary>
        internal static string DISPLAYHELPER_NOHTMLFILE {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOHTMLFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No linked views have beed added yet for this uri. Please use the Select New Linked Views link to add new linked views..
        /// </summary>
        internal static string DISPLAYHELPER_NOLINKEDVIEWS {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOLINKEDVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No media has been linked to this calculator or analyzer. Please use another view..
        /// </summary>
        internal static string DISPLAYHELPER_NOMEDIA {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The selected files could not be saved..
        /// </summary>
        internal static string DISPLAYHELPER_NOSELECTEDFILES {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOSELECTEDFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Clubs subscribe to individual services. Please first select a service..
        /// </summary>
        internal static string DISPLAYHELPER_NOSERVICES {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No clubs have subscriptions to this service. Does the service need to be improved?..
        /// </summary>
        internal static string DISPLAYHELPER_NOSUBSCRIPTIONS {
            get {
                return ResourceManager.GetString("DISPLAYHELPER_NOSUBSCRIPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find the node in the document being calculated. Please run the calculations again..
        /// </summary>
        internal static string ECONOMICS_NONODETOCALCULATE {
            get {
                return ResourceManager.GetString("ECONOMICS_NONODETOCALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The temporary document holding the calculations was not saved properly. Please try running the calculations again..
        /// </summary>
        internal static string ECONOMICS_NOTEMPFILE {
            get {
                return ResourceManager.GetString("ECONOMICS_NOTEMPFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please choose the type of file being analyzed..
        /// </summary>
        internal static string EDIT_CHOOSEFILE {
            get {
                return ResourceManager.GetString("EDIT_CHOOSEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This email is already in use. Please use a different email address..
        /// </summary>
        internal static string EDIT_EMAILINUSE {
            get {
                return ResourceManager.GetString("EDIT_EMAILINUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The original founder of a club can not be deleted from a club by club members. It requires an act of ....
        /// </summary>
        internal static string EDIT_NODELETEFOUNDER {
            get {
                return ResourceManager.GetString("EDIT_NODELETEFOUNDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The original founder of a club must remain in the coordinator role..
        /// </summary>
        internal static string EDIT_NOFOUNDERCHANGE {
            get {
                return ResourceManager.GetString("EDIT_NOFOUNDERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No uris were selected to add, delete, or edit..
        /// </summary>
        internal static string EDIT_NOURISTOEDIT {
            get {
                return ResourceManager.GetString("EDIT_NOURISTOEDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password entered has less than the required 5 characters. Please use a password with at least 5 characters..
        /// </summary>
        internal static string EDIT_PASSWORDLENGTH {
            get {
                return ResourceManager.GetString("EDIT_PASSWORDLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password and confirmed password do not match. Please enter the passwords again..
        /// </summary>
        internal static string EDIT_PASSWORDNOMATCH {
            get {
                return ResourceManager.GetString("EDIT_PASSWORDNOMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The user name is already in use. Please try a different user name..
        /// </summary>
        internal static string EDIT_USERNAMEINUSE {
            get {
                return ResourceManager.GetString("EDIT_USERNAMEINUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The document being edited does not exist yet. Please load the document in the Edits panel. After loading, the edits can then be made..
        /// </summary>
        internal static string EDITHELPER_NOEDITDOC {
            get {
                return ResourceManager.GetString("EDITHELPER_NOEDITDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The selected linked view being edited does not exist yet. Please add the linked view before continuing further..
        /// </summary>
        internal static string EDITHELPER_NOSELECTEDLV {
            get {
                return ResourceManager.GetString("EDITHELPER_NOSELECTEDLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This file has been deleted. Please click on one of the ancestors in the links above the &apos;Submit Edits&apos; button..
        /// </summary>
        internal static string EDITHELPER_PLEASECLICKONANCESTORTOC {
            get {
                return ResourceManager.GetString("EDITHELPER_PLEASECLICKONANCESTORTOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The edits could not be made. Load this panel again and try the edits again..
        /// </summary>
        internal static string EDITS_NOCANDO {
            get {
                return ResourceManager.GetString("EDITS_NOCANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The container.xml file needed by the package could not be found on the web site..
        /// </summary>
        internal static string EPUB_NOCONTAINER {
            get {
                return ResourceManager.GetString("EPUB_NOCONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A file needed for the package could not be found on the web site..
        /// </summary>
        internal static string EPUB_NOFILE {
            get {
                return ResourceManager.GetString("EPUB_NOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following error took place:  .
        /// </summary>
        internal static string ERROR_INTRO {
            get {
                return ResourceManager.GetString("ERROR_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file you are seeking could not be found..
        /// </summary>
        internal static string FILE_NOEXIST {
            get {
                return ResourceManager.GetString("FILE_NOEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file could not be saved..
        /// </summary>
        internal static string FILEIO_CANTSAVEFILE {
            get {
                return ResourceManager.GetString("FILEIO_CANTSAVEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file can not be saved -it appears a data stream has been closed inappropriately..
        /// </summary>
        internal static string FILEIO_STREAMCLOSED {
            get {
                return ResourceManager.GetString("FILEIO_STREAMCLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The html or text file could not be saved in storage (SaveTextURI). The cloud platform&apos;s storage is not working correctly. Please contact DevTreks..
        /// </summary>
        internal static string FILESTORAGE_FILENOSAVEHTMLORTEXT {
            get {
                return ResourceManager.GetString("FILESTORAGE_FILENOSAVEHTMLORTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The posted file could not be saved while writing to data storage..
        /// </summary>
        internal static string FILESTORAGE_FILENOSAVEPOSTEDFILE {
            get {
                return ResourceManager.GetString("FILESTORAGE_FILENOSAVEPOSTEDFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The xml file could not be saved in storage (SaveXmlInURI). The cloud platform&apos;s storage is not working correctly. Please contact DevTreks..
        /// </summary>
        internal static string FILESTORAGE_FILENOSAVEXML {
            get {
                return ResourceManager.GetString("FILESTORAGE_FILENOSAVEXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A summary file associated with the parent file could not be saved..
        /// </summary>
        internal static string FILESTORAGE_FILENOSAVEXMLSUM {
            get {
                return ResourceManager.GetString("FILESTORAGE_FILENOSAVEXMLSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The insertion failed because the parent node for the insertion couldn&apos;t be determined..
        /// </summary>
        internal static string INSERT_NOPARENT {
            get {
                return ResourceManager.GetString("INSERT_NOPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The type of file being uploaded is not recognized by this site. Please contact devtrekkers if you have any questions..
        /// </summary>
        internal static string IOHELPER_BADFILETYPE {
            get {
                return ResourceManager.GetString("IOHELPER_BADFILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not build an html doc. A bug has been logged and will be investigated..
        /// </summary>
        internal static string IOHELPER_CANTBUILD {
            get {
                return ResourceManager.GetString("IOHELPER_CANTBUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not copy an html doc into the package. A bug has been logged and will be investigated..
        /// </summary>
        internal static string IOHELPER_CANTCOPY {
            get {
                return ResourceManager.GetString("IOHELPER_CANTCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The zip file could not be found..
        /// </summary>
        internal static string IOHELPER_CANTFINDZIP {
            get {
                return ResourceManager.GetString("IOHELPER_CANTFINDZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file could not be saved. Please contact devtrekkers about this problem..
        /// </summary>
        internal static string IOHELPER_CANTSAVE {
            get {
                return ResourceManager.GetString("IOHELPER_CANTSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not determine the files to zip. Please select new files..
        /// </summary>
        internal static string IOHELPER_CANTZIP {
            get {
                return ResourceManager.GetString("IOHELPER_CANTZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The files could not be zipped. Please correct the following error and try again:.
        /// </summary>
        internal static string IOHELPER_CANTZIP2 {
            get {
                return ResourceManager.GetString("IOHELPER_CANTZIP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The instructions needed to package the file are missing. An error might have ocurred between you and here. Please try again..
        /// </summary>
        internal static string IOHELPER_NOINSTRUCTS {
            get {
                return ResourceManager.GetString("IOHELPER_NOINSTRUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file being zipped or packaged does not have a name. An error might have ocurred between you and here. Please try again..
        /// </summary>
        internal static string IOHELPER_NONAME {
            get {
                return ResourceManager.GetString("IOHELPER_NONAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The resource could not be saved on: .
        /// </summary>
        internal static string IOHELPER_NOSAVE {
            get {
                return ResourceManager.GetString("IOHELPER_NOSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not determine where the file should be uploaded. Please make sure that javascript is fully enabled on your browser and that this site&apos;s security is set to at least a medium (i.e. trusted) level..
        /// </summary>
        internal static string IOHELPER_NOSAVELOCATION {
            get {
                return ResourceManager.GetString("IOHELPER_NOSAVELOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not determine where to put the file..
        /// </summary>
        internal static string IOHELPER_NOSAVELOCATION2 {
            get {
                return ResourceManager.GetString("IOHELPER_NOSAVELOCATION2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The size of the file being uploaded is too large. Please reduce the file size to.
        /// </summary>
        internal static string IOHELPER_TOOBIG {
            get {
                return ResourceManager.GetString("IOHELPER_TOOBIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The resource was saved successfully on: .
        /// </summary>
        internal static string IOHELPER_YESSAVE {
            get {
                return ResourceManager.GetString("IOHELPER_YESSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not currently a member of any clubs. Please contact the clubs that you wish to join. Once they have added you to their club, this utility can be used..
        /// </summary>
        internal static string MEMBERHELPER_NOTMEMBER {
            get {
                return ResourceManager.GetString("MEMBERHELPER_NOTMEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A discrepency was found between the number of of members subscribing to a service and the actual members belonging to the club. .
        /// </summary>
        internal static string MEMBERREPOSIT_UPDATEAGREEMENTAMOUNT {
            get {
                return ResourceManager.GetString("MEMBERREPOSIT_UPDATEAGREEMENTAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The service agreement could not be updated. A discrepency was found with the isowner property..
        /// </summary>
        internal static string MEMBERREPOSIT_UPDATEAGREEMENTISOWNER {
            get {
                return ResourceManager.GetString("MEMBERREPOSIT_UPDATEAGREEMENTISOWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good bank expiration month..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKENDMONTH {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKENDMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good bank expiration year..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKENDYEAR {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKENDYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good bank number..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKFULLNUMBER {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKFULLNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good bank name..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKNAME {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good short bank number..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKSHORTNUMBER {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKSHORTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good bank state..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKSTATE {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good bank type..
        /// </summary>
        internal static string MEMBERSERVICE_BADBANKTYPE {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADBANKTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good credit card expiration month..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDENDMONTH {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDENDMONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good credit card expiration year..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDENDYEAR {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDENDYEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good credit card number..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDFULLNUMBER {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDFULLNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a credit card name..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDNAME {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good short credit card number..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDSHORTNUMBER {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDSHORTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fillin a good credit card state..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDSTATE {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please fill in a good credit card type..
        /// </summary>
        internal static string MEMBERSERVICE_BADCARDTYPE {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADCARDTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A club can not be inserted. We could not confirm that you are a member..
        /// </summary>
        internal static string MEMBERSERVICE_BADMEMBERFORCLUBINSERT {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADMEMBERFORCLUBINSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The credit card and bank information submitted could not be updated. Please contact DevTreks for further information..
        /// </summary>
        internal static string MEMBERSERVICE_BADUPDATECREDIT {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_BADUPDATECREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please choose an initial region and club group for your club..
        /// </summary>
        internal static string MEMBERSERVICE_CHOOSEGROUPANDREGION {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_CHOOSEGROUPANDREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please choose an initial region and member group for your membership..
        /// </summary>
        internal static string MEMBERSERVICE_CHOOSEMEMBERGROUP {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_CHOOSEMEMBERGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This email is already in use. Please use a different email address for your club email..
        /// </summary>
        internal static string MEMBERSERVICE_CLUB_EMAILINUSE {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_CLUB_EMAILINUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The email for the club you entered could not be found. Please check the address and try again..
        /// </summary>
        internal static string MEMBERSERVICE_CLUB_EMAILNOTFOUND {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_CLUB_EMAILNOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This email is already in use. Please use a different email address for your member email..
        /// </summary>
        internal static string MEMBERSERVICE_MEMBER_EMAILINUSE {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_MEMBER_EMAILINUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The club&apos;s name and email address must be filled out..
        /// </summary>
        internal static string MEMBERSERVICE_MISSINGCLUBDATA {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_MISSINGCLUBDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The new club&apos;s email must be filled out..
        /// </summary>
        internal static string MEMBERSERVICE_MISSINGCLUBEMAIL {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_MISSINGCLUBEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The new club&apos;s name must be filled out..
        /// </summary>
        internal static string MEMBERSERVICE_MISSINGCLUBNAME {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_MISSINGCLUBNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The member&apos;s first name, last name, and email address must be filled out..
        /// </summary>
        internal static string MEMBERSERVICE_MISSINGMEMBERDATA {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_MISSINGMEMBERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter both a password and a confirmation password..
        /// </summary>
        internal static string MEMBERSERVICE_NOPASSWORD {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_NOPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password entered has less than the required 5 characters. Please use a password with at least 5 characters..
        /// </summary>
        internal static string MEMBERSERVICE_PASSWORDLENGTH {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_PASSWORDLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password and the confirmation password do not match..
        /// </summary>
        internal static string MEMBERSERVICE_PASSWORDNOTCONFIRMED {
            get {
                return ResourceManager.GetString("MEMBERSERVICE_PASSWORDNOTCONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The default club could not be set properly..
        /// </summary>
        internal static string MEMBERVIEW_BADDEFAULTCLUB {
            get {
                return ResourceManager.GetString("MEMBERVIEW_BADDEFAULTCLUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The full uri for this content was not set properly..
        /// </summary>
        internal static string MEMBERVIEW_BADURIFULL {
            get {
                return ResourceManager.GetString("MEMBERVIEW_BADURIFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This club has not made any payments, nor has it received any revenues..
        /// </summary>
        internal static string MEMBERVIEW_NOPAYS {
            get {
                return ResourceManager.GetString("MEMBERVIEW_NOPAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No categories have been added yet for this network..
        /// </summary>
        internal static string MEMHELPER_NOCATEGORIES {
            get {
                return ResourceManager.GetString("MEMHELPER_NOCATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No service was set for this uri..
        /// </summary>
        internal static string MEMHELPER_NOSERVICE {
            get {
                return ResourceManager.GetString("MEMHELPER_NOSERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No owned services were found. In order to view the clubs that have subscribed to a service, the service must be an owned service..
        /// </summary>
        internal static string MEMHELPER_NOSERVICES {
            get {
                return ResourceManager.GetString("MEMHELPER_NOSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No owned services were found (note that services can&apos;t start with &apos;00&apos; in their name). In order to view the clubs that have subscribed to a service, the service must be an owned service..
        /// </summary>
        internal static string MEMHELPER_NOSERVICES2 {
            get {
                return ResourceManager.GetString("MEMHELPER_NOSERVICES2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not authorize you. Please log back in..
        /// </summary>
        internal static string MEMHELPER_NOTAUTHORIZED {
            get {
                return ResourceManager.GetString("MEMHELPER_NOTAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please include a normal email address in the format: &apos;someone@somewhere.here&apos; ..
        /// </summary>
        internal static string MEMSERVICE_BADEMAIL {
            get {
                return ResourceManager.GetString("MEMSERVICE_BADEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The email address entered could not be found. Please try again..
        /// </summary>
        internal static string MEMSERVICE_BADEMAIL2 {
            get {
                return ResourceManager.GetString("MEMSERVICE_BADEMAIL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The password entered does not work. Please try re-entering the password again. If you have forgotten your password, please call us for assistance..
        /// </summary>
        internal static string MEMSERVICE_PASSWORDBAD {
            get {
                return ResourceManager.GetString("MEMSERVICE_PASSWORDBAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please enter a password. If you have forgotten your password, please call us for assistance..
        /// </summary>
        internal static string MEMSERVICE_PASSWORDENTER {
            get {
                return ResourceManager.GetString("MEMSERVICE_PASSWORDENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The xml document associated with this uri could not be built..
        /// </summary>
        internal static string MODELHELPERS_BADXMLCONTENT {
            get {
                return ResourceManager.GetString("MODELHELPERS_BADXMLCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This uri can not be displayed. This message usually means that the potential data associated with the uri can be too large to display, or that the uri is only used for navigation not for building content . Please use the uri&apos;s children instead..
        /// </summary>
        internal static string MODELHELPERS_CANTMAKEMODEL {
            get {
                return ResourceManager.GetString("MODELHELPERS_CANTMAKEMODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The model for this uri could not be made. This message usually means that the uri has a bad address (the id could be wrong)..
        /// </summary>
        internal static string MODELHELPERS_CANTMAKEMODEL1 {
            get {
                return ResourceManager.GetString("MODELHELPERS_CANTMAKEMODEL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either networks have not been selected yet by your current club, or the club needs to load the list containing them. Please contact one of the club&apos;s coordinators and have them select at least one network or load their list of networks..
        /// </summary>
        internal static string NETWORKS_NOTSELECTED {
            get {
                return ResourceManager.GetString("NETWORKS_NOTSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not set.
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Repository cannot be null.
        /// </summary>
        internal static string REPOSITORY_NOTNULL {
            get {
                return ResourceManager.GetString("REPOSITORY_NOTNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The resource being retrieved could not be found in blob storage..
        /// </summary>
        internal static string RESOURCES_NOBLOB {
            get {
                return ResourceManager.GetString("RESOURCES_NOBLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The resource being retrieved does not have the file needed to load it..
        /// </summary>
        internal static string RESOURCES_NOFILE {
            get {
                return ResourceManager.GetString("RESOURCES_NOFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The type of file you are uploading is not presently allowed. Please contact the network about adding support for this type of file..
        /// </summary>
        internal static string RESOURCES_NOFILETYPE {
            get {
                return ResourceManager.GetString("RESOURCES_NOFILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The category list could not be saved for display..
        /// </summary>
        internal static string SAVECATEGORIES_NOCANDO {
            get {
                return ResourceManager.GetString("SAVECATEGORIES_NOCANDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The resources associated with this uri could not be retrieved. Please check the resource&apos;s attributes, including the filename. If the problem can&apos;t be fixed, try uploading a new file with new filename, or deleting this resource..
        /// </summary>
        internal static string SQLCONTENT_NORESOURCES {
            get {
                return ResourceManager.GetString("SQLCONTENT_NORESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The xml document could not be saved..
        /// </summary>
        internal static string SQLCONTENT_NOSAVE {
            get {
                return ResourceManager.GetString("SQLCONTENT_NOSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The file could not be saved..
        /// </summary>
        internal static string SQLCONTENT_NOSAVE2 {
            get {
                return ResourceManager.GetString("SQLCONTENT_NOSAVE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No selections were available for insertion. Please make selections and submit the selections again..
        /// </summary>
        internal static string SQLCONTENT_NOSELECTS {
            get {
                return ResourceManager.GetString("SQLCONTENT_NOSELECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A default xml node, used to start an xml document, was mistakenly deleted from the database. Please alert  the web platform host..
        /// </summary>
        internal static string SQLXML_MISSINGDBDEFAULTNODE {
            get {
                return ResourceManager.GetString("SQLXML_MISSINGDBDEFAULTNODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The base xml document could not be converted to xhtml. Try rebuilding the base xml (by running new calculations). If the error persists the bad xml is probably coming from an error in a calculator or analyzer..
        /// </summary>
        internal static string STYLEHELPER_BADXMLORHTML {
            get {
                return ResourceManager.GetString("STYLEHELPER_BADXMLORHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A linked list could not be found. Please ask the list&apos;s author to check the list&apos;s tag name:.
        /// </summary>
        internal static string STYLEHELPER_NOLINKEDLIST {
            get {
                return ResourceManager.GetString("STYLEHELPER_NOLINKEDLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &lt;br /&gt;&lt;span&gt;&lt;strong&gt;A linked list could not be found. Please ask the list&apos;s author to check the list&apos;s tag name:&lt;/strong&gt;&lt;/span&gt;.
        /// </summary>
        internal static string STYLEHELPER_NOLINKEDLIST2 {
            get {
                return ResourceManager.GetString("STYLEHELPER_NOLINKEDLIST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stylesheet could not be found (StylesheetHelper.GetStylesheet())..
        /// </summary>
        internal static string STYLEHELPER_NOSTYLE {
            get {
                return ResourceManager.GetString("STYLEHELPER_NOSTYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stylesheet could not be retrieved from cache (or it could not be read using the path specfied in the getfromcache method)..
        /// </summary>
        internal static string STYLEHELPER_NOSTYLEFROMCACHE {
            get {
                return ResourceManager.GetString("STYLEHELPER_NOSTYLEFROMCACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  This contention message can be erased by clicking on any tab..
        /// </summary>
        internal static string TAB_CLICK_TO_ERASE {
            get {
                return ResourceManager.GetString("TAB_CLICK_TO_ERASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Proof.
        /// </summary>
        internal static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Account Id: .
        /// </summary>
        internal static string TITLE_ACCOUNTID {
            get {
                return ResourceManager.GetString("TITLE_ACCOUNTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Application: .
        /// </summary>
        internal static string TITLE_APPLICATION {
            get {
                return ResourceManager.GetString("TITLE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Admin Message:.
        /// </summary>
        internal static string TITLE_FULLMSG {
            get {
                return ResourceManager.GetString("TITLE_FULLMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Id: .
        /// </summary>
        internal static string TITLE_ID {
            get {
                return ResourceManager.GetString("TITLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Point of contention: .
        /// </summary>
        internal static string TITLE_MESSAGE {
            get {
                return ResourceManager.GetString("TITLE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Node Name: .
        /// </summary>
        internal static string TITLE_NODENAME {
            get {
                return ResourceManager.GetString("TITLE_NODENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Service Id: .
        /// </summary>
        internal static string TITLE_SERVICEID {
            get {
                return ResourceManager.GetString("TITLE_SERVICEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SubApplication: .
        /// </summary>
        internal static string TITLE_SUBAPPLICATION {
            get {
                return ResourceManager.GetString("TITLE_SUBAPPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following property could not be updated: .
        /// </summary>
        internal static string UPDATE_BADPROPERTY {
            get {
                return ResourceManager.GetString("UPDATE_BADPROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The initial club and list that starts this collection was not retrieved properly..
        /// </summary>
        internal static string VIEWS_NOACCOUNTINIT {
            get {
                return ResourceManager.GetString("VIEWS_NOACCOUNTINIT", resourceCulture);
            }
        }
    }
}
