//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorsContracts.GeneralMessages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Messages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorsContracts.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An observation is missing from the analysis. Please make sure that calculations have been run on all observations. Also make sure that the type of calculation selected is appropriate for this analysis..
        /// </summary>
        public static string ADDIN_MISSINGOBSERVATION {
            get {
                return ResourceManager.GetString("ADDIN_MISSINGOBSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A document needed to run the calculations is missing..
        /// </summary>
        public static string ADDINHELPER_MISSINGDOC {
            get {
                return ResourceManager.GetString("ADDINHELPER_MISSINGDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The type of calculator being run could not be determined. Are you sure this is the right addin?.
        /// </summary>
        public static string ADDINHELPER_NOCALCTYPE {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOCALCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator could not be loaded. Please try running the calculations again. If the problem continues, please reload the calculator again..
        /// </summary>
        public static string ADDINHELPER_NOCALCULATOR {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOCALCULATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Files could not be found to analyze. Are you sure that devpackpart files have been added to the database?.
        /// </summary>
        public static string ADDINHELPER_NODEVPACKPARTS {
            get {
                return ResourceManager.GetString("ADDINHELPER_NODEVPACKPARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator does not have a needed file extension type..
        /// </summary>
        public static string ADDINHELPER_NOFILEEXTENSIONTYPE {
            get {
                return ResourceManager.GetString("ADDINHELPER_NOFILEEXTENSIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The statistical analysis could not be run..
        /// </summary>
        public static string ANALYSES_CANTRUN {
            get {
                return ResourceManager.GetString("ANALYSES_CANTRUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please choose the type of aggregation to run..
        /// </summary>
        public static string ANALYSES_CHOOSEAGGTYPE {
            get {
                return ResourceManager.GetString("ANALYSES_CHOOSEAGGTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please choose the type of analysis to run..
        /// </summary>
        public static string ANALYSES_CHOOSEONE {
            get {
                return ResourceManager.GetString("ANALYSES_CHOOSEONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The analyses could not be saved because of an id mismatch between the pre-analysis analyzer and post-analysis analyzer..
        /// </summary>
        public static string ANALYSES_ID_MISMATCH {
            get {
                return ResourceManager.GetString("ANALYSES_ID_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either the node count or the file count was out of acceptable bounds for the analysis being run..
        /// </summary>
        public static string ANALYSES_INDEX_OUTOFBOUNDS {
            get {
                return ResourceManager.GetString("ANALYSES_INDEX_OUTOFBOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The analyzer chosen has not been completed yet. Please choose another analysis..
        /// </summary>
        public static string ANALYSES_NOANALYZER {
            get {
                return ResourceManager.GetString("ANALYSES_NOANALYZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The analysis could not find any files to analyze. Has the base calculator been run first? Please double check the file being analyzed..
        /// </summary>
        public static string ANALYSES_NOFILES {
            get {
                return ResourceManager.GetString("ANALYSES_NOFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The step was not completed successfully. Please check the data used in the analyzer and try again. Make sure this analyzer is compatible with this uri. If the problem persists, contact the analyzer&apos;s author (using the feedback link on the Intro page of the analyzer)..
        /// </summary>
        public static string ANALYSES_URI_MISMATCH {
            get {
                return ResourceManager.GetString("ANALYSES_URI_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This analyzer analyzes base calculator data. The base calculator data has not been run yet. Please run the base  calculations first..
        /// </summary>
        public static string ANALYZER_BASECALCS_MISSING {
            get {
                return ResourceManager.GetString("ANALYZER_BASECALCS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator file could not be found. Please be sure that the calculator being used has a default calculator document..
        /// </summary>
        public static string CALCSHELPER_FILE_NOTFOUND {
            get {
                return ResourceManager.GetString("CALCSHELPER_FILE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to See the expenses for the last period being grown..
        /// </summary>
        public static string CALCULATOR_SEELAST_PERIOD {
            get {
                return ResourceManager.GetString("CALCULATOR_SEELAST_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculations could not be saved because of an id mismatch between the pre-calculation calculator and post-calculation calculator.
        /// </summary>
        public static string CALCULATORS_ID_MISMATCH {
            get {
                return ResourceManager.GetString("CALCULATORS_ID_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The calculator could not be found. Are you sure this is the right addin or extension for this calculator?.
        /// </summary>
        public static string CALCULATORS_MISSING {
            get {
                return ResourceManager.GetString("CALCULATORS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A host for this calculator could not be found..
        /// </summary>
        public static string CALCULATORS_MISSING_HOST {
            get {
                return ResourceManager.GetString("CALCULATORS_MISSING_HOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The base document needed to run calculations has not been built. Please use the Make Base command to build the missing document. Once built it only needs to be rebuilt if changes have been made in this data..
        /// </summary>
        public static string CALCULATORS_MISSINGBASEDOC {
            get {
                return ResourceManager.GetString("CALCULATORS_MISSINGBASEDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The step was not completed successfully. Please check the data used in the calculator and try again. Make sure this calculator is compatible with this uri. If the problem persists, contact the calculator&apos;s author (using the feedback link on the Intro page of the calculator)..
        /// </summary>
        public static string CALCULATORS_URI_MISMATCH {
            get {
                return ResourceManager.GetString("CALCULATORS_URI_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This uri can not be calculated using this calculator. Please choose another calculator..
        /// </summary>
        public static string CALCULATORS_WRONG_ONE {
            get {
                return ResourceManager.GetString("CALCULATORS_WRONG_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to % ci.
        /// </summary>
        public static string CI_PCT {
            get {
                return ResourceManager.GetString("CI_PCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This error can result from having a distribution outside the bounds of QT..
        /// </summary>
        public static string DATA_BADDISTRIBUTION {
            get {
                return ResourceManager.GetString("DATA_BADDISTRIBUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The first row of data in a DataSetURL must contain column names. The names are missing..
        /// </summary>
        public static string DATA_NOCOLUMNNAMES {
            get {
                return ResourceManager.GetString("DATA_NOCOLUMNNAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This url is incorrect. Please make sure the file has been uploaded to a base resource correctly and make sure the url is correct..
        /// </summary>
        public static string DATAURL_BAD {
            get {
                return ResourceManager.GetString("DATAURL_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The data set is not formatted correctly. Please read the instructions in the associated tutorial..
        /// </summary>
        public static string DATAURL_BADDATA {
            get {
                return ResourceManager.GetString("DATAURL_BADDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Data URL must point to one or more csv-delimited files holding the data being analyzed. One or more files are missing. Please read the instructions for this algorithm..
        /// </summary>
        public static string DATAURL_MISSING {
            get {
                return ResourceManager.GetString("DATAURL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Either the original DevPack file needed to find the linked view was not available, or the file did not contain the needed linked view. Please try initialized the calculator again..
        /// </summary>
        public static string GETDEVPACKCALC_NOLINKEDVIEW {
            get {
                return ResourceManager.GetString("GETDEVPACKCALC_NOLINKEDVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Indicator properties are missing or wrong. Do indicator labels correspond to dataset labels? Do indicators have correct algorithms? Please recheck all indicator properties..
        /// </summary>
        public static string INDICATORS_BAD {
            get {
                return ResourceManager.GetString("INDICATORS_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to : jace.net parser error.
        /// </summary>
        public static string JACE_BASIC {
            get {
                return ResourceManager.GetString("JACE_BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The joint data url needed by this dataset is missing. The indexed dataset is: .
        /// </summary>
        public static string JDATAURL_BAD {
            get {
                return ResourceManager.GetString("JDATAURL_BAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Joint Data URL must point to one or more csv-delimited files with information about the indicator correlations. One or more files are missing. Please read the instructions for this algorithm..
        /// </summary>
        public static string JOINTURL_MISSING {
            get {
                return ResourceManager.GetString("JOINTURL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to lower .
        /// </summary>
        public static string LOWER {
            get {
                return ResourceManager.GetString("LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This calculation uses Cholesky matrixes which could not be generated from the correlation matrix. Recheck the correlation matrix..
        /// </summary>
        public static string MATRIX_BADCHOL {
            get {
                return ResourceManager.GetString("MATRIX_BADCHOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A correlation matrix could not be generated from the data in Data URL. The data must contain at lease three observations for each correlated indicator and the number of rows must be identical for each indicator..
        /// </summary>
        public static string MATRIX_BADCOR {
            get {
                return ResourceManager.GetString("MATRIX_BADCOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The data stored in the Data URL can&apos;t be used to generate a correlation matrix. Does each correlated indicator have at least 3 observations and do they have the same number of observations? Do the indicators stored in the Joint Data file match the same indicators used in Data URL?.
        /// </summary>
        public static string MATRIX_BADCORDATA {
            get {
                return ResourceManager.GetString("MATRIX_BADCORDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This calculation uses eigenvalue matrixes which could not be generated from the correlation matrix. Recheck the correlation matrix..
        /// </summary>
        public static string MATRIX_BADEIGEN {
            get {
                return ResourceManager.GetString("MATRIX_BADEIGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A matrix could not be made from the data in the url. Please upload a good matrix..
        /// </summary>
        public static string MATRIX_BADFORMAT {
            get {
                return ResourceManager.GetString("MATRIX_BADFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please make sure to upload either an initial zeroes, or real, correlation matrix and reference it using the Joint DataURL property..
        /// </summary>
        public static string MATRIX_MISSING {
            get {
                return ResourceManager.GetString("MATRIX_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The matrix does not start with a csv row of indicators..
        /// </summary>
        public static string MATRIX_NOCINDICATORS {
            get {
                return ResourceManager.GetString("MATRIX_NOCINDICATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An aggregating element could not be added to the observations document..
        /// </summary>
        public static string OBSERVATIONS_MISSING_AGGREGATOR {
            get {
                return ResourceManager.GetString("OBSERVATIONS_MISSING_AGGREGATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An existing observation could not be found in the observations document..
        /// </summary>
        public static string OBSERVATIONS_MISSING_ONE {
            get {
                return ResourceManager.GetString("OBSERVATIONS_MISSING_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An existing observation could not be replaced correctly in the observations document..
        /// </summary>
        public static string OBSERVATIONS_MISSING_REPLACEMENT {
            get {
                return ResourceManager.GetString("OBSERVATIONS_MISSING_REPLACEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The files used to run the analysis and build the text file could not be found. Please contact the owner of this calculator or analyzer..
        /// </summary>
        public static string OBSERVATIONS_NOFILES_SAVETEXT {
            get {
                return ResourceManager.GetString("OBSERVATIONS_NOFILES_SAVETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The best combination of machinery could not be determined using these operations or components. Make sure the base operations or components have been calculated using good machinery-calculated inputs..
        /// </summary>
        public static string RESOURCESTOCKS_NOMACH1SELECTSCHEDULE {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS_NOMACH1SELECTSCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The collections of power inputs and nonpower inputs could not be made. Please check the underlying inputs in this analysis..
        /// </summary>
        public static string RESOURCESTOCKS_NOPOWERORNONPOWERINPUTS {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS_NOPOWERORNONPOWERINPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The scheduling and selection calculations could not be run..
        /// </summary>
        public static string RESOURCESTOCKS_NOSIMULATEDANNEALING {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS_NOSIMULATEDANNEALING", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The initial net present value calculator for an operation or component was not run. Please make sure that each operation or component has a good net present value calculation..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOBASENPVOPCOMP {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOBASENPVOPCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The base budget stock collection needed for analyzing timeliness penalties was not built correctly. Please contact the author of this analyzer using the Feedback link on the Init panel of the analyzer..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOBASESTOCKBUDGET {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOBASESTOCKBUDGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The base time period stock collection needed for analyzing timeliness penalties was not built correctly. Please contact the author of this analyzer using the Feedback link on the Init panel of the analyzer..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOBASESTOCKTIMEPERIODS {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOBASESTOCKTIMEPERIODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The best machinery stock calculations could not be run correctly. Please check the underlying machinery..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOBESTTIMELINESSCALCS {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOBESTTIMELINESSCALCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stock collection needed for analyzing machinery costs was not built correctly. Please contact the author of this analyzer using the Feedback link on the Init panel of the analyzer..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOMACHINERYLIST {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOMACHINERYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The best machinery stocks could not be converted to a data format that allows them to be displayed (they could not be correctly serialized)..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOSERIALIZEBEST {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOSERIALIZEBEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The size range collection needed for the analysis could not be built correctly. Please check the inputs to make sure they have correct size ranges. If the problem still persists, please contact the author of this analyzer using the Feedback link on the Init panel of the analyzer..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOSIZERANGES {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOSIZERANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The stock collection needed for analyzing timeliness penalties was not built correctly. Please contact the author of this analyzer using the Feedback link on the Init panel of the analyzer..
        /// </summary>
        public static string RESOURCESTOCKS2A_NOTIMELINESSOBJECT {
            get {
                return ResourceManager.GetString("RESOURCESTOCKS2A_NOTIMELINESSOBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The initial random samples needed by this calculation could not be built. Has all of the distribution properties for each correlated indicator been filled in correctly?.
        /// </summary>
        public static string SAMPLES_BADDIST {
            get {
                return ResourceManager.GetString("SAMPLES_BADDIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The correlated random samples needed by this calculation could not be built. Has all of the distribution properties for each correlated indicator been filled in correctly and has the inital correlation matrix been filled in correctly?.
        /// </summary>
        public static string SAMPLES_BADRND {
            get {
                return ResourceManager.GetString("SAMPLES_BADRND", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to sampled descriptive statistics.
        /// </summary>
        public static string STATS_DESC1 {
            get {
                return ResourceManager.GetString("STATS_DESC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to N,Total,Mean,Median,StdDev,Var,Min,Max.
        /// </summary>
        public static string STATS_DESC2 {
            get {
                return ResourceManager.GetString("STATS_DESC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to observed descriptive statistics.
        /// </summary>
        public static string STATS_DESC3 {
            get {
                return ResourceManager.GetString("STATS_DESC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to sampled cumulative density function.
        /// </summary>
        public static string STATS_DESC4 {
            get {
                return ResourceManager.GetString("STATS_DESC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to observed cumulative density function.
        /// </summary>
        public static string STATS_DESC5 {
            get {
                return ResourceManager.GetString("STATS_DESC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This data does not have sampled descriptive statistics..
        /// </summary>
        public static string STATS_DESC6 {
            get {
                return ResourceManager.GetString("STATS_DESC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to upper .
        /// </summary>
        public static string UPPER {
            get {
                return ResourceManager.GetString("UPPER", resourceCulture);
            }
        }
    }
}
